export const topJournalists = [
  {
    id: '1',
    name: 'Sarah Mitchell',
    outlet: 'TechCrunch',
    beat: 'AI & Machine Learning',
    section: 'Technology',
    latestArticle: 'The Future of Generative AI in Enterprise Software',
    articleCount: 247,
    lastPublished: '2 hours ago',
    email: 'sarah.mitchell@techcrunch.com',
    twitter: '@sarahmitchell',
    linkedin: 'sarahmitchell',
    rating: 4.8,
    expertise: ['Artificial Intelligence', 'Startups', 'SaaS'],
  },
  {
    id: '2',
    name: 'David Chen',
    outlet: 'The Wall Street Journal',
    beat: 'Finance & Markets',
    section: 'Business',
    latestArticle: 'Federal Reserve Signals Shift in Interest Rate Policy',
    articleCount: 412,
    lastPublished: '5 hours ago',
    email: 'david.chen@wsj.com',
    twitter: '@davidchen',
    rating: 4.9,
    expertise: ['Banking', 'Economics', 'Market Analysis'],
  },
  {
    id: '3',
    name: 'Maria Rodriguez',
    outlet: 'Reuters',
    beat: 'Climate & Environment',
    section: 'World',
    latestArticle: 'Global Carbon Emissions Reach New Peak Despite Climate Pledges',
    articleCount: 328,
    lastPublished: '1 day ago',
    twitter: '@mariarodriguez',
    linkedin: 'mariarodriguez',
    rating: 4.7,
    expertise: ['Climate Change', 'Sustainability', 'Environmental Policy'],
  },
  {
    id: '4',
    name: 'James Patterson',
    outlet: 'The New York Times',
    beat: 'Politics',
    section: 'National',
    latestArticle: 'Senate Debate Heats Up Over Infrastructure Bill',
    articleCount: 589,
    lastPublished: '3 hours ago',
    email: 'j.patterson@nytimes.com',
    rating: 4.9,
    expertise: ['US Politics', 'Policy', 'Elections'],
  },
];

export const allJournalists = [
  ...topJournalists,
  {
    id: '5',
    name: 'Emily Watson',
    outlet: 'TechCrunch',
    beat: 'Cybersecurity',
    section: 'Technology',
    latestArticle: 'Major Data Breach Affects Millions of Users',
    articleCount: 156,
    lastPublished: '4 hours ago',
    email: 'emily.watson@techcrunch.com',
    twitter: '@emilywatson',
    rating: 4.6,
    expertise: ['Security', 'Privacy', 'Data Protection'],
  },
  {
    id: '6',
    name: 'Michael Zhang',
    outlet: 'TechCrunch',
    beat: 'Startups & Venture Capital',
    section: 'Business',
    latestArticle: 'Record Breaking Quarter for Tech Startup Funding',
    articleCount: 203,
    lastPublished: '6 hours ago',
    twitter: '@michaelzhang',
    linkedin: 'michaelzhang',
    rating: 4.7,
    expertise: ['Venture Capital', 'Fundraising', 'IPOs'],
  },
  {
    id: '7',
    name: 'Lisa Anderson',
    outlet: 'The Wall Street Journal',
    beat: 'Corporate Strategy',
    section: 'Business',
    latestArticle: 'Tech Giants Announce Major Restructuring Plans',
    articleCount: 378,
    lastPublished: '7 hours ago',
    email: 'lisa.anderson@wsj.com',
    rating: 4.8,
    expertise: ['Corporate News', 'M&A', 'Leadership'],
  },
  {
    id: '8',
    name: 'Robert Taylor',
    outlet: 'Reuters',
    beat: 'International Trade',
    section: 'Business',
    latestArticle: 'New Trade Agreement Reshapes Global Commerce',
    articleCount: 291,
    lastPublished: '1 day ago',
    twitter: '@roberttaylor',
    rating: 4.5,
    expertise: ['Trade Policy', 'Global Markets', 'Economics'],
  },
];

export const recentSearches = [
  { id: '1', query: 'TechCrunch', timestamp: '10 minutes ago', count: 6 },
  { id: '2', query: 'The Wall Street Journal', timestamp: '1 hour ago', count: 2 },
  { id: '3', query: 'Reuters Climate', timestamp: '2 hours ago', count: 1 },
  { id: '4', query: 'NYT Politics', timestamp: '5 hours ago', count: 4 },
  { id: '5', query: 'AI Journalists', timestamp: '1 day ago', count: 3 },
];

export const outlets = [
  'TechCrunch',
  'The Wall Street Journal',
  'Reuters',
  'The New York Times',
  'Bloomberg',
  'Financial Times',
  'The Washington Post',
  'CNN',
  'BBC News',
  'Forbes',
];